
LLM_PROVIDER = "anthropic"
LLM_MODEL = "MiniMax-M2.5"

# Anthropic (MiniMax) 配置
ANTHROPIC_API_KEY = "sk-api-lOOJhAfdvrmPxe3ldKJhrLEFtXWQl9QPcg3qbASd-O94qKkaPmfob-rNpJgd_K_rvzsVj7rq8cvaarGbDvphDtBIZZxZhEaCadgBQ2d7gWrouEbvG9THcfE"
ANTHROPIC_BASE_URL = "https://api.minimaxi.com/anthropic"

# OCR 配置
OCR_PROVIDER = "baidu"
BAIDU_OCR_API_KEY = "Z18HOsACWndDUgvYcDPczXiy"
BAIDU_OCR_SECRET_KEY = "sYAqeDKXOeKgLIGYdAcpRZLe5t6vPvaI"
